### ISSUE TITLE
latest version of Markdown

### ISSUE THREAD

**Issue by dirk777** [cwacek/python-jsonschema-objects#110]
python-jsonschema-objects needs Markdown 2.4. Other modules I use need at least Markdown 2.6.9. Could you please upgrade Markdown to latest version or change dependecy to Markdown>=2.4?

**Comment by warwing** [comment]
We also have an issue with markdown - one of our other dependencies requires the latest version (2.11.0) - but we don't use the markdown functionality of python-jsonschema-objects.

Would it be possible to make markdown an optional dependency - by removing the markdown relevant imports from __init__.py and moving the markdown dependency to the "setup_requires" section?

**Comment by brianmaissy** [comment]
+1
@cwacek, Is there a reason it requires specifically 2.4 and not >= 2.4?
I'd be happy to open a PR if you'd like.
