### ISSUE TITLE
Literal values are now set to the validator, not the value

### ISSUE THREAD

**Issue by agoose77** [cwacek/python-jsonschema-objects#112]
https://github.com/cwacek/python-jsonschema-objects/blob/3072b61b0e8ab010c97a5cdaca2fb2ed8f84d8a2/python_jsonschema_objects/classbuilder.py#L795

I'm not sure that this is intended behaviour. Instead, I think we want to set the _value_ of the validator

**Comment by rascalking** [comment]
Haven't tried to grok the logic in that method yet, but I was seeing weirdness where literals seemed to be returning validators.  Came up with a minimal repro test:

```
import python_jsonschema_objects as pjo

schema = {
    'title': 'Test schema',
    'type': 'object',
    'properties': {
        'stringProp': {'type': 'string'},
    },
    'required': ['stringProp'],
}

builder = pjo.ObjectBuilder(schema)
ns = builder.build_classes()
instance = ns.TestSchema(stringProp='A string')
assert 'A str' in instance.stringProp
```

This test fails under `0.3.0` with
```
Traceback (most recent call last):
  File "./test.py", line 16, in <module>
    assert 'A str' in instance.stringProp
TypeError: argument of type 'test_schema/stringProp' is not iterable
```

But passes under `0.3.1`.
