### ISSUE TITLE
Accessing object definition within array

### ISSUE THREAD

**Issue by ddlenz** [cwacek/python-jsonschema-objects#122]
I have the following schema
{
	"title": "Example2",
	"type": "array",
	"items": {
		"title": "exampleitem",
		"type": "object",
		"properties": {
			"name": {
				"type": "string"
			}
		}
	}
}

and code

      schema = json.loads('{"title": "Example2","type": "array","items": {"title" : "exampleitem", "type": "object","properties": {"name": { "type": "string" }}}}')
      builder = pjs.ObjectBuilder(schema).build_classes()
      responseFactory = builder.Example2

Is there a way to get an instance of the exampleitem object? I've tried referencing the items object title property ("exampleitem") as well as a few other things, but no luck.

**Comment by cwacek** [comment]
This was answered at some point with an updated README, but basically, you want to access it with `builder.Exampleitems`. Names get camelcased unless `standardize_names=False` is provided at build time.
