### ISSUE TITLE
Unexpected anonymousField

### ISSUE THREAD

**Issue by lewis6991** [cwacek/python-jsonschema-objects#141]
```python
ns = pjs.ObjectBuilder({
    "id": "Example",
    "type": "object",
    "properties": {
        "prop": {
            "title": "prop",
            "type": "array",
            "items": { "type": "string" }
        }
    }
}).build_classes()
print(dir(ns))
```

Output:
```
['Example', 'Prop<anonymousField>']
```

Why is `Prop` an `anonymousField`? Is this expected?

**Comment by cwacek** [comment]
It’s because prop is an array type with an items designator, so this is actually referring to the array types validator, which is in fact anonymous

**Comment by lewis6991** [comment]
Hmm ok. If I remember correctly, when I made prop the top level it was parsed as non-anonymous. I'm on my phone right now so I can't verify.

```
"title": "prop",
"type": "array",
"items": { "type": "string" }
```

**Comment by lewis6991** [comment]
Sorry, the behaviour here isn't clear to me. What determines whether a jsonchema object/array parses to an anonymous class or not? Are top level objects treated differently? I'm definitely not an expert when it comes to jsonchema so I'm probably misunderstanding something.

Thanks for developing this project.
