### ISSUE TITLE
Please update the library to use the newer jsonschema 3.0.0a3

### ISSUE THREAD

**Issue by tincumagic** [cwacek/python-jsonschema-objects#154]
Please add jsonschema 3.0.0a3 in requirements that supports jsonschema-draft-7.

**Comment by cwacek** [comment]
Yes, in my limited spare time. I would prefer to wait to bump the dependency version until jsonschema releases a non-alpha or beta version, but at the rate of their updates that might happen soon.

**Comment by jeromekelleher** [comment]
Just FYI @cwacek , jsonschema is now released at 3.0.1 (https://pypi.org/project/jsonschema/). An update would be much appreciated, if you have time, as it's causing a bit of hassle downstream. Thanks for the really useful library!

**Comment by kennydo** [comment]
I made #158 after investigating whether this library already supports `jsonschema` 3.0.0, and it looks like it works! Please take a look and let me know what you think.

**Comment by kennydo** [comment]
Using the latest version of `python-jsonschema-objects` (0.3.7) with the latest version of `jsonschema` (3.0.1) has been working fine for me, so I think this issue can be closed.

**Comment by cwacek** [comment]
Fixed in #158 (released in 0.3.7)
