### ISSUE TITLE
Validation of property names

### ISSUE THREAD

**Issue by steinymity** [cwacek/python-jsonschema-objects#170]
I just noticed that apparently propertyNames are not validated.

Considering this schema
```
{
    "title": "Test Object",
    "type": "object",
    "propertyNames": {
        "type": "string",
        "pattern": "^[a-z]{3}$"
    },
    "additionalProperties": {
        "type": "number"
    }
}
```
and this code
```
>>> ob=pjs.ObjectBuilder(schema)
>>> ns=ob.build_classes()
>>> ns['x']=32
>>> ns=ob.build_classes()
>>> x=ns.TestObject()
>>> x['y']=42
>>> x.serialize()
'{"y": 42}'
```
I would expect the assignment `x['y']=42` to raise a `ValidationError`.

As far as I can see, such a routine could be add to `ExtensibleValidator.instantiate`. Would it be possible to use `MakeLiteral` to validate the name against a schema?

**Comment by cwacek** [comment]
Is ‘propertyNames’ a validator in the spec? It doesn’t validate because I didn’t realize that was a thing.

It’s definitely doable.

**Comment by steinymity** [comment]
Yeah, at least in the current spec, it's mentioned. It's a way to implement dictionaries with requirements for the keys (which must be strings, though): https://json-schema.org/latest/json-schema-validation.html#rfc.section.6.5.8

**Comment by cwacek** [comment]
Not stale! Totally valid, just haven’t been able to get to it

**Comment by trivialkettle** [comment]
Still not implemented right?

**Comment by cwacek** [comment]
Nope. Happy to look at a PR if you have one.On May 15, 2023, at 8:00 AM, trivialkettle ***@***.***> wrote:﻿
Still not implemented right?
