### ISSUE TITLE
Output classes to python file

### ISSUE THREAD

**Issue by nrchakradhar** [cwacek/python-jsonschema-objects#171]
I am a new user of this project. The classes generated seem to suit my need exactly. I wanted to know if its possible to generate .py files for the classes probably with default values set?

**Comment by cwacek** [comment]
Unfortunately not. Actually generating valid python files for the classes is extremely complicated.

If you want to extend the generated classes, you can create your own classes that subclass the generated classes using something like:

```
generated_classes = pjo.ObjectBuilder().build_classes()

class MyClass(generated_classes.BaseClass):
    pass
```

**Comment by nrchakradhar** [comment]
Thanks for sharing this information.
