### ISSUE TITLE
Detail JSON Schema draft version support

### ISSUE THREAD

**Issue by Relequestual** [cwacek/python-jsonschema-objects#174]
It doesn't look like you detail the draft version of JSON Schema you support.
Could you add this detial to the read-me please?

draft-7 is latest, but draft-8 is coming pretty soon.

**Comment by cwacek** [comment]
As of right now, the only thing that I can definitively say is supported is draft-4 (for better or worse). That was the current version when the last major keyword support update was made. Someone pointed out that certain draft-6 support isn't available in #170.

If you want the README updated, propose a PR.

**Comment by Relequestual** [comment]
Sure. I understand. Lots of things still only do draft-4.
Additionally, it could be useful if you throw an error if a schema is provided which identifies as a different draft version. Would you like me to file a new issue for this?
I wouldn't be able to make a PR for this given I don't know python, but it's basically checking if the root schema value `$schema` is equal to the draft-4 URI or not.
