### ISSUE TITLE
Request: flag for build_classes to ignore "Not Implemented"

### ISSUE THREAD

**Issue by mattysan** [cwacek/python-jsonschema-objects#187]
I have a case where I would have liked to have built an incomplete class from a schema. We use "anyOf" in the schema, which is currently not supported by this module, but I could have continued doing what I needed to do if I had a flag to tell build_classes to ignore those kinds of exceptions. Food for thought in lieu of implementing support for some of these items.

**Comment by cwacek** [comment]
@mattysan can you provide an example of how you'd use the library with a schema that uses anyOf (and thus can't be handled properly)?

**Comment by mattysan** [comment]
I don't want to go into detail but the general process is that we needed a script to generate some binary test data that has an associated .json file. The original script only created the binary data, but I wanted to mod it to also dump a semi-complete version of the .json file as well, as a convenience, with the intent that it would be a "start" for the person and they could then go in and edit it as needed. (The json file points to the binary file, along with some other metadata generated by the script)

Someone here built a parser for this json file that has an associated schema. I wanted to use the schema (and your module) to build an object in my convenience script that I could then modify certain fields and dump to a file. The items marked as "anyOf" are a subsection of the JSON file that I just wanted to default to a single option or leave empty for now, but because it is marked as anyOf, I was unable to use your module to create the class to edit it in an intelligent way. I have worked around this by creating a dictionary in the script with the fields I need. It's not terrible but I would have preferred to use your module to make it a little cleaner, so that the schema remained the sole source of correctness.

**Comment by cwacek** [comment]
Hmm. I suppose a flag could allow anyOf to just be a dictionary. It could even be validated with some kind of wrapper, it just can’t be instantiated into an actual specific object.

I’ll think about this - not sure when I’ll have the time to dig in, so if you have a proposed change I’m happy to start there.
