### ISSUE TITLE
Inconsistent behavior for null and non-null properties  

### ISSUE THREAD

**Issue by reece** [cwacek/python-jsonschema-objects#200]
**Describe the bug**

Null and non-null values are handled inconsistently depending on the value and how the value is set.

**Example Schema and code**
```
>>> import io
>>> import python_jsonschema_objects as pjs
>>> pjs.__version__
'0.3.13'

>>> schema = {
>>>     "$id": "test",
>>>     "$schema": "http://json-schema.org/draft-04/schema#",
>>>     "title": "test",
>>>     "type": "object",
>>>     "definitions": {
>>>         "myclass": {
>>>             "type": "object",
>>>             "properties": {
>>>                 "p1": {
>>>                     "type": ["integer", "null"],
>>>                     "default": 0,
>>>                 },
>>>                 "p2": {
>>>                     "type": ["integer", "null"],
>>>                     "default": None,
>>>                 },
>>>             },
>>>         }
>>>     }
>>> }
>>> builder = pjs.ObjectBuilder(schema)
>>> classes = builder.classes


>>> c = classes.Myclass()
>>> c
<myclass p1=<Literal<int> 0> p2=None>
>>> c.as_dict()
{'p1': 0}


>>> d = classes.Myclass(p2=None)
>>> d
<myclass p1=<Literal<int> 0> p2=None>
>>> d.as_dict()
{'p1': 0}


>>> d.p2 = None
>>> d
<myclass p1=<Literal<int> 0> p2=<Literal<NoneType> None>>
>>> d.as_dict()
{'p1': 0, 'p2': None}

```

**Expected behavior**

The most straightforward behavior is for all values to be explicit and for None to be a valid value for nullable fields (e.g., `type: ["integer", "null"]`). In my opinion, such behavior should be the starting point as it is least likely to surprise users. Thus, an expression like `classes.Myclass().as_dict()` above would explicitly serialize all properties with default values or None.

A more complicated behavior is to suppress values that are identical to the default value during serialization. This may be what is intended by the current implementation. However, note that the last stanza of code (`d.p2 = None`) is setting the property to the default and that the property is now included in the dictionary.

**Comment by reece** [comment]
@cwacek : I would appreciate a comment on this issue and PR #201.

**Comment by cwacek** [comment]
Grr - I have to turn off that stale bot - it’s more annoying than useful.

I’ll try and take a look this week

**Comment by cwacek** [comment]
Okay, so I took a look at this. You're specifically referring to the expectation for nullable fields _with a default_ right? For instance, extending your object definition to this:

```{
             "type": "object",
             "properties": {
                 "p1": {
                     "type": ["integer", "null"],
                     "default": 0,
                 },
                 "p2": {
                     "type": ["integer", "null"],
                     "default": None,
                 },
                 "p3": {
                     "type": ["integer", "null"],
                 },
             },
         }
```

Would the expected serialization be:  `{'p1': 0, 'p2': None}` or `{'p1': 0, 'p2': None, 'p3': None}`
