### ISSUE TITLE
Does not use Draft7 Metaschema

### ISSUE THREAD

**Issue by dohrayme** [cwacek/python-jsonschema-objects#203]
**Describe the bug**
Even if you set the schema on ObjectBuilder, it internally uses the Draft4 metaschema anyway.

        validatorClass = validatorClass or Draft4Validator
        meta_validator = validatorClass(Draft4Validator.META_SCHEMA)

gives:

Failed validating 'minItems' in schema['properties']['definitions']['additionalProperties']['properties']['required']

whereas using  validatorClass.META_SCHEMA (Draft7) schema validates fine

**Comment by cwacek** [comment]
Closed by #212
