### ISSUE TITLE
Json reader pipeline

### ISSUE THREAD

**Issue by kolis** [cwacek/python-jsonschema-objects#22]
This project seems very focused on exporting json documents conforming to a specified schema specification.

I want to go the other way, I have schema specification and a bunch of json documents that I need to parse. I was hoping to find an example showing this, how to load and validate an existing json document into a class instance generated by this framework. I was expecting something like
```
try:
    person = ns.load(jsonData)
    print('firstName: ' + person.firstName + ', lastName: ' + person.lastName)
except ValidationError as e:
    print('syntax error: ' + str(e))
```
where the jsonData would be validated against the loaded schema

With this workflow it would also be nice if the generated bindings could be stored as python code instead of being generated during runtime. If I have a schema that does not change much I can reuse the generated classes if I'm able to import them in my parser. Updating the generated classes can easily be managed by any build system that detects changes updated modification dates on the scheme files.

**Comment by farshidce** [comment]
for this use case I have been able to successfully use the function called "from_json" which takes a string and converts it to the object.

this has worked for me for simple and complex objects

example 
Person().from_json()
