### ISSUE TITLE
draft-06/7 support

### ISSUE THREAD

**Issue by AdamJel** [cwacek/python-jsonschema-objects#221]
**What are you trying to do?**
I would like to use builder for building based on schema draft 6 or 7, since they are published.

**Is this a currently unsupported jsonschema directive? If so, please link to the documentation**

[Schema-06](https://json-schema.org/draft-06/json-schema-release-notes.html)

**Recognized errors**

`build_classes()` fails on `KeyError '$id'`.

**Comment by rhass** [comment]
+1 - I could use this as well.

**Comment by cwacek** [comment]
@AdamJel can you provide a stripped down version of the schema you're trying to use? It should work with 06 - it just doesn't have all the validations and warns you about it.

Having a exemplar schema that isn't working would help track it down.

**Comment by hinoue** [comment]
I'm trying to use this library with `https://www.schemastore.org/schemas/json/sarif-2.1.0-rtm.4.json`

It gives this, `UserWarning: Schema version http://json-schema.org/draft-07/schema# not recognized. Some keywords and features may not be supported.` on `pjs.ObjectBuilder()`, and gives the error, `NotImplementedError: anyOf is not supported as bare property` on `build_classes()`.

**Comment by cwacek** [comment]
@hinoue See discussion on #51 to deal with schemas that contain `anyOf`. You can pass `any_of='use-first'` to `build_classes()` to make it use that workaround.
