### ISSUE TITLE
No module named 'jsonschema.compat' 

### ISSUE THREAD

**Issue by davimenezesoli** [cwacek/python-jsonschema-objects#223]
**Describe the bug**
We are getting the error saying that the module is named `jsonschema.compat` couldn't be found. This is happening because this file was removed from the `jsonschema` package. See: https://github.com/Julian/jsonschema/issues/843

**Example Schema and code**
```
Traceback (most recent call last):
  File "./client.py", line 6, in <module>
    import python_jsonschema_objects as pjs
  File "/usr/local/lib/python3.6/dist-packages/python_jsonschema_objects/__init__.py", line 12, in <module>
    from jsonschema.compat import iteritems
ModuleNotFoundError: No module named 'jsonschema.compat'
```

**Expected behavior**
The error should not happen. Looks like the other package is changing the method to use `.items()` instead of `iteritems()`. Maybe the same thing can be updated here.

**Comment by cwacek** [comment]
Fixed in #224
