### ISSUE TITLE
Schema Composition `oneOf` required Support

### ISSUE THREAD

**Issue by prokod** [cwacek/python-jsonschema-objects#228]
**What are you trying to do?**
We use this library to automatically generate classes to validate outgoing web requests, and trying to use `oneOf` like so:
```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Request Body",
  "required": [
     ...
  ],
  "oneOf": [
             { "allOf": [
               { "not": { "required": [
          	     "resizeMachine" ] } },
               { "not": { "required": [
                 "resizeBootDisk" ] } },
               { "not": { "required": [
                 "addDataDisk" ] } },
               { "not": { "required": [
                 "resizeDataDisk" ] } }
             ] },
          
          { "required": [
              "resizeMachine",
              "resizeBootDisk",
              "addDataDisk",
              "resizeDataDisk"
            ]
          }
        ]
```

**Is this a currently unsupported jsonschema directive? If so, please link to the documentation**

This seems to be supported currently when checked here: https://www.jsonschemavalidator.net/ with schema draft 04

**What happens currently**
Unsupported Exception is thrown by the library

**Comment by cwacek** [comment]
@prokod if this is still an issue you'd like to see resolved, can you add two examples of payloads you'd consider valid for each side of this `oneOf` constraint?

**Comment by cwacek** [comment]
This may now be supported under certain circumstances in version 0.5.1. See discussion in #51.
