### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by littlej-x** [cwacek/python-jsonschema-objects#231]
**Describe the bug**
Bellow is an example of usage of this library that causes a memory leak. Running this code will quickly use up the system's memory. With use of a memory profiler, I traced the source of the leak to line 323 of classbuilder.py `if isinstance(val, ProtocolBase):`. At this point `val` is `"city1"` and `self` is `city1 <address_<anonymous> attributes: city>` from bellow example.

**Example Schema and code**
```
import python_jsonschema_objects as pjo

schema = {
    "title": "person",
    "type": "object",
    "properties": {
        "address": {
            "type": "object",
            "properties": {
                "city": {"type": "string"},
            },
            "required": ["city"]
        }
    }
}


def person_from_data():
    classes = pjo.ObjectBuilder(schema)    
    Person = classes.get_class('person')
    Address = classes.get_class('person/address_<anonymous>')

    return Person(address=Address(city="city1"))


def main():
    while True:
        person_from_data()


main()
```

**Expected behavior**
No memory leak should result from use of this library.

**Comment by cwacek** [comment]
This is the same as issue #210. You’re seeing this because you’re calling build_classes inside the loop. Move that out and you won’t see the memory increase each time.

**Comment by littlej-x** [comment]
Ah ok, thank-you.

**Comment by littlej-x** [comment]
Why then does this example not cause memory usage to increase.

```
import python_jsonschema_objects as pjo

schema = {
    "title": "person",
    "type": "object",
    "properties": {
        "address": {
            "type": "object",
            "properties": {
                "city": {"type": "string"},
            }
        }
    }
}


def person_from_data():
    classes = pjo.ObjectBuilder(schema)    
    Person = classes.get_class('person')
    Address = classes.get_class('person/address_<anonymous>')

    person = Person(address=Address())
    person.address.city = "city1"

    return person


def main():
    while True:
        person_from_data()


main()
```

Where the line `isinstance(val, ProtocolBase):` is never reached
?

**Comment by cwacek** [comment]
That’s a good question. I’ll need to look at that in more detail.
