### ISSUE TITLE
Does not support jsonschema 4.18

### ISSUE THREAD

**Issue by s-t-e-v-e-n-k** [cwacek/python-jsonschema-objects#235]
jsonschema 4.18 is a major re-work, and as such, breaks the API. For right now, you should probably pin the dependency to <4.18, but investigating failures (or adding a CI build using it) would be amazing.

**Comment by cwacek** [comment]
I don't have time to investigate right now, so I pinned it for now. I'm actually going to re-open this issue because it's still valid. If you, or anyone else, has time to investigate the issue and propose a fix I'll take a look.
