### ISSUE TITLE
0.4.3 pins jsonschema <4.1.8, but it should be <4.18

### ISSUE THREAD

**Issue by EliahKagan** [cwacek/python-jsonschema-objects#237]
#235 correctly notes incompatibility with jsonschema 4.*18* and recommends pinning <4.18, which appears to have been the intention of #236. But #236 pins <4.*1.8* instead. This keeps it much farther back than necessary, which based on context appears unintended.

The effect is that installing python-jsonschema-objects 0.4.3 requires a downgrade to jsonschema 4.1.2 (there was no 4.1.8 version), which came out more than a year before the latest known-compatible version, 4.17.3.

I've opened PR #238 to change the pinning in `setup.py` from <4.1.8 to <4.18.

**Comment by cwacek** [comment]
In addition to accepting @EliahKagan's MR fixing this issue, I have deleted the 0.4.3 tag from Github and "yanked" it from PyPi, so hopefully people won't run into this issue just because they do a pip install unless they explicitly specify that version.
