### ISSUE TITLE
Support for json-schema/2020

### ISSUE THREAD

**Issue by kacperpaczos** [cwacek/python-jsonschema-objects#268]
Please consider providing support or creating a compatibility table for json-schema standards:
I am using: https://json-schema.org/draft/2020-12/schema
And I encounter a "bug":
```
/home/kacper/Dokumenty/Bennet/.venv/bin/python /home/kacper/Dokumenty/Bennet/models/classes/anvil.class.py
/home/kacper/Dokumenty/Bennet/.venv/lib/python3.10/site-packages/python_jsonschema_objects/__init__.py:60: UserWarning: Schema version https://json-schema.org/draft/2020-12/schema not recognized. Some keywords and features may not be supported.
  warnings.warn(
```

**Comment by cwacek** [comment]
What's the bug?

**Comment by cwacek** [comment]
Closing for now. Can re-open if additional details provided.

**Comment by kacperpaczos** [comment]
I would be happy if the README includes the latest supported version of the JSON schema.
