### ISSUE TITLE
Unable to determine valtype

### ISSUE THREAD

**Issue by kacperpaczos** [cwacek/python-jsonschema-objects#275]
I have a JSON schema:
```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://jsonschema.net/anvil",
  "title": "Anvil Base",
  "description": "This 'anvil' scheme is a template for a class managing projects for Bennet",
  "type": "object",
  "properties": {
    "name": { "type": "string", "default": "my-new-project" },
    "version": { "type": "string", "default": "1.0.0", "pattern": "^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)$" },
    "description": { "type": "string", "default": "My New Project description." },
    "main": { "type": "string", "minLength": 1, "default": "index.js" },
    "scripts": {
      "type": "array",
      "items": {
        "title": "script",
        "type": "object",
        "properties": {
          "name": { "type": "string", "default": "build" },
          "command": { "type": "string", "default": "meson compile -C builddir" }
        }
      }
    },
    "repository": {
      "title": "repository",
      "type": "object",
      "properties": {
        "url": { "type": "string", "default": "https://example.com/your-username/my-new-project" },
        "vcs": { "type": "string", "default": "git" }
      }
    },
    "author": { "type": "string", "default": "Your Name <you@example.com>" },
    "license": { "type": "string", "minLength": 1, "default": "GPLv3" },
    "dependencies": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "default": []
    },
    "devDependencies": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "default": []
    }
  }
}
```
I have a base class:
```
import json
import python_jsonschema_objects as pjo
from common.common import ic

try:
    with open('models/schemes/anvil_base_schema.json', 'r') as file:
        schema = json.load(file)
except FileNotFoundError:
    ic("Error: Could not read the file 'models/schemes/anvil_base_schema.json'")
    schema = {}

main_builder = pjo.ObjectBuilder(schema)
main_namespace = main_builder.build_classes()
AnvilBase = main_namespace.AnvilBase

AnvilBase.scripts = []

scripts_builder = pjo.ObjectBuilder(schema['properties']['scripts']['items'])
scripts_namespace = scripts_builder.build_classes()
AnvilBase.scripts.append(scripts_namespace.Script())

repository_builder = pjo.ObjectBuilder(schema['properties']['repository'])
repository_namespace = repository_builder.build_classes()
repository_instance=repository_namespace.Repository()
AnvilBase.repository = repository_instance
```

I have a class:
```
class Anvil(AnvilBase):
    def __init__(self, filesystem, root="root", *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.filesystem = FileSystemManager()
```
**Problem is that I can't define an object in the classic way due to the validator:**
`self.filesystem = FileSystemManager()`

Additional information:
```
SCHEMA_TYPE_MAPPING = (
    ("array", list),
    ("boolean", bool),
    ("integer", six.integer_types),
    ("number", six.integer_types + (float,)),
    ("null", type(None)),
    ("string", six.string_types),
    ("object", dict),
)
```

Here is problem, we have None and out of list error:
```
valtype = [
                k
                for k, t in validators.SCHEMA_TYPE_MAPPING
                if t is not None and isinstance(val, t)
            ] 
```

**Comment by cwacek** [comment]
> Problem is that I can't define an object in the classic way due to the validator:
> self.filesystem = FileSystemManager()

What do you mean by this? What is the actual error or stacktrace?

I think I see what you're running into - the class won't let you assign `filesystem` because that's not a property in your schema and the object is being validated using your schema. I'm not sure this is a supported use case, since the whole point is to generate classes from schemas and check that they're valid. 

However, have you tried using `setattr` - no guarantees it will work, but it might bypass the validators.

**Comment by kacperpaczos** [comment]
I will try to do it or something similar tomorrow. Please, try running the latest version of my project, then you will see more information. Use ./bennet entrypoint. Perhaps the solution is simple and easy for someone with more experience.
https://github.com/kacperpaczos/Bennet

**Comment by kacperpaczos** [comment]
I believe the problem lies in the fact that PJO initially loads types from the class, such as filesystem, and then from the file. Do you think it's possible to change the order? First, load types from JSON, and then extend them from normal classes.

**Comment by cwacek** [comment]
I honestly don’t understand what you’re first sentence means.

The issue is more likely that the generated classes override a bunch of
internals like setattr, so when you subclass from them you get those
effects. You could try having the PJO object as a delegated object in your
class instead of subclassing.

I’m not going to run your project to see the error, sorry. If you create a
basic test case, I’ll work from that.
