### ISSUE TITLE
Obsolete jsonpatch and jsonpointer requirements

### ISSUE THREAD

**Issue by lockie** [cwacek/python-jsonschema-objects#37]
Hello!
Could you please update versions of jsonpatch and jsonpointer in your requirements.txt? They both have error installing on system with C locale (e.g. http://readthedocs.org environment) - see stefankoegl/python-json-pointer#8.
Latest versions, according to pip, are jsonpatch-1.13 and jsonpointer-1.10.

**Comment by cwacek** [comment]
Fixed in 0.0.19
