### ISSUE TITLE
patternProperties

### ISSUE THREAD

**Issue by johanfforsberg** [cwacek/python-jsonschema-objects#44]
The "patternProperties" keyword can be used to match property names to schemas using regular expressions. Could this be supported by jsonschema-objects? I suppose it might be an obscure feature but it's very useful in my use case.

**Comment by stardust85** [comment]
+1

**Comment by cwacek** [comment]
Can one of you give me an example of why you would do this?

It's not impossible, but the problem is that the generated class would have to check every attribute access and assignment to see (1) if it matches a regular expression, (2) if that property is actually in use, and (3) dynamically apply a type to that property if it is. This is complex, so I want to understand the use case before going down that road.

**Comment by stardust85** [comment]
imagine this json file

```json
{
  "Czech Republic": {
      "capital": "Prague",
      "num_inhabitants": 1040000
  },
 "Slovakia": {
      "capital": "Bratislava",
      "num_inhabitants": 5000000
  }
}
```

Some json files really use this. But when re-thinking of this, it is probably better to change the schema to:

```json
[{
      "name": "Czech Republic",
      "capital": "Prague",
      "num_inhabitants": 1040000
  },
  {
      "name": "Slovakia",
      "capital": "Bratislava",
      "num_inhabitants": 5000000
  }]
```

But what if you can't change the schema (you get the documents from a 3rd party source)?

**Comment by cwacek** [comment]
Does that mean you'd use a patternProperties regular expression with `.*`?
Isn't this case better handled by using additionalProperties as below:

```
{
   "properties": {},
   "additionalProperties": {
      "type": "object",
      "properties": { ... }
   }
}
```

**Comment by stardust85** [comment]
Ah, I didn't realize that this could be the way. OK, I will try to change my schema to use this...

**Comment by johanfforsberg** [comment]
My use case is something like this:
```json
{
    "servers": {
        "Database/2": {},
        "PowerSupply/A": {}
    }
}
```
where I want to make sure that the keys in "servers" always match the regex "\w+/\w+".

I agree that the array form proposed by stardust85 is another form that would work, but to me using an array somehow implies that the set of servers is ordered, which in my case it is not. And since the server names are always unique anyway, this format works nicely.

I would not want the library to become overcomplicated just to support this minor feature though. I just thought I'd file an issue since it is part of the standard :)

**Comment by stardust85** [comment]
exactly, in my case the keys (in the exapmle names of countries) are also unique and don't have any ordering. And also the regex can be sometimes userful - in case of the countries, nobody would allow a cuntry called "123" :)

I hope the implementation is possible... 

@cwacek , you can create a feature branch for it and if people like your initial implementation you propose above, they can contribute if it needs some enhancements/testing/coverage by tests...

**Comment by stardust85** [comment]
Awesome, thanks!
