### ISSUE TITLE
NotImplementedError: anyOf is not supported as bare property

### ISSUE THREAD

**Issue by hramasub** [cwacek/python-jsonschema-objects#51]
This code 
``
with open('ComputerSystemCollection.json') as schema_file:
    root_schema = json.load(schema_file)

builder = pjso.ObjectBuilder (root_schema)
ns = builder.build_classes()
``

to generate binding for the following schema: 
http://redfish.dmtf.org/schemas/v1/ComputerSystemCollection.json

results in the following error:

Traceback (most recent call last):
  File "./test.py", line 14, in <module>
    ns = builder.build_classes()
  File "/usr/lib/python2.7/site-packages/python_jsonschema_objects/**init**.py", line 78, in build_classes
    builder.construct(uri, defn)
  File "/usr/lib/python2.7/site-packages/python_jsonschema_objects/classbuilder.py", line 418, in construct
    ret = self._construct(uri, _args, *_kw)
  File "/usr/lib/python2.7/site-packages/python_jsonschema_objects/classbuilder.py", line 426, in _construct
    "anyOf is not supported as bare property")
**NotImplementedError: anyOf is not supported as bare property**

**Comment by cwacek** [comment]
@hramasub I'm not likely to fix this in the near future. The problem is that `anyOf` has a particularly terrible meaning for generating class instances: it allows the data to match "one or more of the provided schemas". Since python_jsonschema_objects effectively generates a class wrapper for each schema, it's not clear how to handle the `anyOf` property, since which class wrapper you get back is going to be non-deterministic. 

For most uses where you would use `anyOf`, you can use `oneOf`, and `oneOf` has much improved semantics because it designates a 1-1 link between generated class instance and schema.

`anyOf` is a useful motif for *validation*, because you all you care about is whether or not there's a match, but it doesn't make much sense for class/wrapper generation.

**Comment by cwacek** [comment]
The only thing I can think that would be reasonable is a flag like: `any of=“first-match”`, which would cause the resolver to generate to the first matching schema in the list.

That would not be the default behavior, and obviously wouldn’t actually match the jsonschema semantics, but would allow you to use the library for schemas with this keyword if you understood what it would do.

**Comment by rmspeers** [comment]
Yes, that makes sense. I tried a hack outside the library to monkey-patch my schema with a similar effect for now - with plenty of warnings given. I think that behavior would be a reasonable one to at least handle the keyword. I'll try to take a look at the lib code more and see if I can figure out where to add that in the architecture when I have a chance.

**Comment by cwacek** [comment]
I'd be happy to look at a PR when you have one.

**Comment by rmspeers** [comment]
@cwacek I can move this to a new issue if useful, but in working on this I ran into an issue in my test creation, where:
1. when I don't set strict=True, it doesn't seem to be raising a ValidationError even on invalid emails (I see valdiator is determining false, but the exception isn't propagating to be thrown)
2. when I set strict=True, which I did to sanity check if that mattered, it doesn't seem to see the property in the below example:

```
def test_simple_array_anyOf():
    basicSchemaDefn = {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "title": "Test",
        "properties": {
            "ExampleAnyOf": {"$ref": "#/definitions/exampleAnyOf"}
        },
        "required": ["ExampleAnyOf"],
        "type": "object",
        "definitions": {
            "exampleAnyOf": {
                "oneOf":
                    {"type": "string", "format": "email"},
                    {"type": "string", "maxlength": 0},
                ]
            }
        },
    }

    builder = pjo.ObjectBuilder(basicSchemaDefn)

    ns = builder.build_classes(strict=True)
    ns.Test().from_json('{"ExampleAnyOf" : "test@example.com"}')
```

**Comment by cwacek** [comment]
Can you make a draft PR with the test setup and I can take a look at it
later?

**Comment by rmspeers** [comment]
Created https://github.com/cwacek/python-jsonschema-objects/pull/266. That does not have a test for the strict issue mentioned above, it just is for anyOf simplifying to oneOf with the first anyOf item being used.

**Comment by cwacek** [comment]
It was included in release `0.5.1` cut yesterday. @rmspeers @hramasub

**Comment by rmspeers** [comment]
When I integrated this upstream, I found that although it worked for my simple example, it didn't work when it was nested in a real-world example. My fault. It looks like `kw` needs to be passed down to calls to `construct` inside `def _build_object(self, nm, clsdata, parents, **kw):`.

**Comment by rmspeers** [comment]
@cwacek - I had a chance to look at this per my above note and submit a brief PR for your review to see if that should fix this in nested/edge cases. https://github.com/cwacek/python-jsonschema-objects/pull/280
