### ISSUE TITLE
Add strict mode to object creation (required)

### ISSUE THREAD

**Issue by itielshwartz** [cwacek/python-jsonschema-objects#52]
Hi,
the doc says:
""" An instance of a class generated from the provided
    schema. All properties will be validated according to
    the definitions provided. However, whether or not all required
    properties have been provide will *not* be validated.
""

it's very important for me that all required properties are in the object, and i would like to throw an error in case missing required field on creation time, also i think it's a logical behavior .

i would like to add "strict" key-argument to build_classes, 
in case of strict mode the object will validate itself upon creation,

already made a local fork , can i make a pr and add this?

**Comment by cwacek** [comment]
Please do! I'm happy to pull in PRs as long as they don't break other
functionality or massively rewrite everything.

If you do implement this, please include some tests for the behavior.

**Comment by itielshwartz** [comment]
created a pr https://github.com/cwacek/python-jsonschema-objects/pull/53

**Comment by cwacek** [comment]
Looked good to me. Just merged it.
