### ISSUE TITLE
UnicodeDecodeError on Windows with non-UTF8 preferred encoding

### ISSUE THREAD

**Issue by jar3b** [cwacek/python-jsonschema-objects#65]
Hello.
I use Python 3.5.2 on Windows 10 (with non-English localization).
When I try to load schema from disk (by creating `ObjectBuilder()` instance) then I have this error:

```
  File "D:\Soft\Python35\lib\site-packages\python_jsonschema_objects\__init__.py", line 34, in __init__
    self.schema = json.loads(fin.read())
  File "D:\Soft\Python35\lib\encodings\cp1251.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 195: character maps to <undefined>
```

Code fails 'cos Windows has cp1251 as so-called locale preferred encoding but my schema has utf-8.

It's strange why in `ObjectBuilder.__init__()` used `open(uri)` for loading file, but in `ObjectBuilder.relative_file_resolver()` used `codecs.open(path, 'r', 'utf-8')` for same action (and usage of second decision is a right way in my opinion at least in my case).
Rewriting `open()` to `codecs.open()` in `ObjectBuilder` constructor solves this issue.

**Comment by cwacek** [comment]
If you open a PR for your fix for this, I'm happy to merge it (assuming it doesn't break other things).
