### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by SteveHarrison82** [cwacek/python-jsonschema-objects#67]
Following features or helper methods wud be nice, this library will truly become a service to handle all sorts of flat file

A. Generate n objects with default values corresponding to built class
B. De/serialize all fields
C. De/serialze selected set of fields
D. Sorting of objects generated based on builder class w.r.t certain fields

**Comment by cwacek** [comment]
Please provide an example of what this interface would look like. I can't
quite visualize what you're asking for.

**Comment by rama-bornfree** [comment]
I believe, I have not explored the library enough, but I am really excited. I will summarize in coming days

Thank you and sorry for bothering

Thanks for the package!

**Comment by cwacek** [comment]
Since jsonschema defines properties as a dictionary, they are inherently not ordered. This means it's still not possible to know what the ordering is. For more generic ordering (such as alphabetically), I think you're better off doing it outside of this library.
