### ISSUE TITLE
generate typed python code for mypy

### ISSUE THREAD

**Issue by graingert** [cwacek/python-jsonschema-objects#68]
It would be really neat to be able to generate typed Python source code out of json schemas

**Comment by cwacek** [comment]
Can you explain further? In theory this could be accomplished by writing the runtime generated classes out to disk, but the code isn't likely to be *pretty*, and I'm not sure I understand the utility.

**Comment by graingert** [comment]
So you can do type checking on code that uses the objects

**Comment by cwacek** [comment]
Oh, using some sort of static type checker? Interesting. I'll think about
the best way to do this (I suspect it's kinda complicated). Runtime type
checks can obviously be done using the generated objects.

**Comment by graingert** [comment]
this is the python standard type checking: mypy

**Comment by cwacek** [comment]
I don't think this is feasible at present. This library supports both Python 2 and 3, and the only way to apply mypy to Py2 is with type annotation comments. Since we just generate runtime objects (not source code), this is going to be hard to create.

**Comment by ikonst** [comment]
Since your objects are generated in runtime, the path forward is to generate .pyi type stubs that are there to instruct mypy (and IDEs aware of typing such as PyCharm). Those type stubs can use the Python 3 syntax for typing, by the way.

**Comment by ikonst** [comment]
Since your objects are generated in runtime, the path forward is to generate .pyi type stubs that are there to instruct mypy (and IDEs aware of typing such as PyCharm). Those type stubs can use the Python 3 syntax for typing, by the way.

**Comment by mlaradji** [comment]
@graingert @ikonst There is a new (untested? abandoned?) project that converts JSON schema to python classes source code (https://github.com/microsoft/jschema-to-python). It works nicely with `mypy`, but can be a bit of a hassle to set up properly, and I'm not sure if it handles all possible JSON schema. I wonder if we can draw inspiration from it to add mypy support to `python-jsonschema-objects`?
