### ISSUE TITLE
Ref problem

### ISSUE THREAD

**Issue by FrankWessels** [cwacek/python-jsonschema-objects#75]
I am trying to get this nice python ui for json files (using json schema) to work, but I ran into some problems. I am trying to understand your code but it will take a while, so I am hoping for a quick answer / solution by posting this issue here.

I have several files linked like this:
Person.json
{
	"$ref": "Person/PersonV1.json"
}

The validation using the python jsonschema package works just fine, had to add a resolver for dealing with all the relative path refs.

For your package I used "RefResolutionError" solution, but I same to get a problem af another nature. When running:

import python_jsonschema_objects as pjs
builder = pjs.ObjectBuilder('some_path/Person.json')
builder.build_classes()

I get

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-18-7dcbdab4421b> in <module>()
----> 1 builder.build_classes()

C:\Miniconda2\lib\site-packages\python_jsonschema_objects\__init__.py in build_classes(self, strict)
    116             builder.construct(uri, defn)
    117 
--> 118         nm = self.schema['title'] if 'title' in self.schema else self.schema['id']
    119         nm = inflection.parameterize(six.text_type(nm), '_')
    120 

KeyError: 'id'
---------------------------------------------------------------------------

So are files with only a reference not allowed (yet)?

**Comment by reece** [comment]
```
self.schema['title'] if 'title' in self.schema else self.schema['id']
```

I had the same issue. Schema must have a id if they do not have a title. Try adding a title.
