### ISSUE TITLE
Update requirements

### ISSUE THREAD

**Issue by rolandjitsu** [cwacek/python-jsonschema-objects#81]
I'm having some issues with installing this package alongside https://github.com/jupyter-widgets/ipywidgets and jupyter notebooks as they depend on `jsonschema>=2.4` (or another one of their deps depends on it) whereas this package is fixed at `v2.3.0`.

Could the requirements for this package be a bit more flexible? It also applies for pandocfilters package.

**Comment by raviv** [comment]
+1
