### ISSUE TITLE
Full support for Draft4 of the schema

### ISSUE THREAD

**Issue by llvieira** [cwacek/python-jsonschema-objects#83]
Hi guys,

It's a great implementation for JSON Schemas in Python, but I would like to know if you intend to implement the full support for Draft4 or if it's possible to do this considering the complexity of generate class instances with the new keywords of the Draft4.

Thanks!

**Comment by cwacek** [comment]
Are there particular Draft4 keywords that are missing that you'd like to see?

**Comment by llvieira** [comment]
@cwacek the particular keyword would be: **anyOf**. It's possible to include the support for this keyword? Unfortunately I guess that we'll have problems with non-deterministic behaviors. :/

**Comment by cwacek** [comment]
This is actually already supported for array item constraints, i.e. the
schema below is handled correctly. Given what had to be done to support it
for arrays, it might not be too hard to do it for "bare" properties.

Do you have an example of a schema that uses `oneOf` in the way you want?

schema = {
+ "$schema": "http://json-schema.org/schema#",
+ "id": "test",
+ "type": "object",
+ "properties": {
+ "list": {
+ "type": "array",
+ "items": {"oneOf": [
+ {"$ref": "#/definitions/foo"},
+ {
+ "type": "object",
+ "properties": {
+ "bar": {"type":"string"}
+ },
+ "required": ["bar"]
+ }
+ ]},
+ }
+ },
+ "definitions": {
+ "foo": {
+ "type": "string"
+ }
+ }
+ }

On Sun, Oct 29, 2017 at 9:54 PM, Lucas Lima Vieira <notifications@github.com

**Comment by cwacek** [comment]
This is actually already supported for array item constraints, i.e. the
schema below is handled correctly. Given what had to be done to support it
for arrays, it might not be too hard to do it for "bare" properties.

Do you have an example of a schema that uses `oneOf` in the way you want?

```json
{"$schema": "http://json-schema.org/schema#",
"id": "test",
"type": "object",
"properties": {
"list": {
"type": "array",
"items": {"oneOf": [
{"$ref": "#/definitions/foo"},
{
"type": "object",
"properties": {
"bar": {"type":"string"}
},
"required": ["bar"]
}
]},
}
},
"definitions": {
"foo": {
"type": "string"
}
}
```

**Comment by llvieira** [comment]
This schema is about the keyword `oneOf`, but what I really want to know is about the keyword `anyOf`. The `oneOf` works fine, but I don't know if `anyOf` is already supported.

**Comment by cwacek** [comment]
Sorry, you're right. Brain fart. Let me think about it again.

**Comment by llvieira** [comment]
No problem, @cwacek.

**Comment by dpwrussell** [comment]
@cwacek Hey, is there any update on this? I am looking to create some objects from a draft4 schema.

Thanks
